### ISSUE TITLE
Parse table level primary key constraints

### ISSUE THREAD

**Issue by luxint** [iafisher/sqliteparser#8]
Hi,

I noticed that this create table statement is not parsed:

create table t1 (c1 text,c2 text,primary key(c1,c2))

as far as I know this I the only way to create a compound primary key in sqlite.

**Comment by iafisher** [comment]
Hi, thanks for the bug report. I've fixed this on the master branch. Do you need a new release to PyPI?

**Comment by luxint** [comment]
Hi Ian,,

Thanks for the quick fix! No need for me for an imminent release to PyPI
